---
title: "Psychological therapies for Depression and Anxiety"
format: 
    html:
      code-link: true
      toc: true 
      toc-depth: 2
      toc-title: "Table of Contents"
editor: source
---

# About this document

This document compiles the list of recommended psychological therapies for Depression and Anxiety in the UK General practice. It benefits from relevant guidance from NICE for management and treatment of depression and anxiety, including:

-   [Depression in adults: treatment and management](https://www.nice.org.uk/guidance/ng222/chapter/Recommendations)
-   [Generalised anxiety disorder and panic disorder in adults: management](https://www.nice.org.uk/guidance/cg113/chapter/Recommendations)

Further, it highlights how psychological therapies are coded in SNOMED-CT using [Opencodelist](https://www.opencodelists.org), a platform based on OpenSafely for sharing and creating codelists.

## Psychological therapies for Depression

The psychological therapies below are offered uniquely or in combinations for management of depression, and sometimes with anti-depressant based on severity, needs and patient's preference

-   **Guided self-help**: Printed or digital self-help materials on key psychological therapies including cognitive behavioural therapy

-   **Cognitive Behavioural Therapy (CBT)**: Focuses on how thoughts and beliefs could be modified to reshape behaviour. CBT is offered either individually or in group depending on patient's preference

-   **Behavioural Activation**: Recommended for recognising patterns in activities that affect mood and avoidance, and developing practical plans to reduce avoidance and improve mood. It can be provided individually or in group

-   **Group Exercise**: Focuses on group physical activity to benefit from peer support

-   **Group mindfulness and meditation**: Uses a programme such as mindfulness-based cognitive therapy. It is designed to increase awareness and recognition of thoughts and feelings

-   **Interpersonal psychotherapy**: Focuses on identifying how interpersonal relationships or circumstances are related to feelings of depression and modifying interpersonal responses

-   **Counselling**: Helps emotional processing, identification of solutions and coping mechanisms

-   **Short-term psychodynamic psychotherapy (STPP)**: Useful for recognising difficult feelings in significant relationships and and stressful situations

-   **Individual problem solving**: Targets identification of problems, generating and implementing alternative solutions

-   **Behavioural couples therapy**: Targets solving relationship challenges contributing to depression

-   **Electroconvulsive therapy**: It involves sending small electrical current through the brain to intentionally trigger a brief seizure

-   **Transcranial Magnetic Therapy**: Uses magnetic field to stimulate nerve cells in the brain, especially those involved in mood regulation

## Psychological therapies for Anxiety (Generalised Anxiety Disorder and Panic Disorder)

A step-care model is recommended by NICE for the management of anxiety. The model recommends range of low-intensity to high-intensity psychological therapies based on severity

Low-intensity therapies (first-line intervention following monitoring)

-   **Individual guided self-help**

-   **Individual non-facilitated self-help**

-   **Psycho-education**

High-intensity therapies

-   **Cognitive Behavioural Therapy**

-   **Applied Relaxation**: Involves learning muscle relaxation techniques during anxiousness or in situations that could trigger anxiousness

## Coding of psychological therapies within SNOMED-CT

This section highlights preliminary insights on how the psychological therapies are coded in SNOMED-CT

-   Returned search terms for therapies such as CBT, Behavioural Activation, Exercise therapy, Interpersonal psychotherapy and applied relaxation are not specific to anxiety or depression. This implies that pattern of coding for psychological therapies should be interpreted cautiously

-   Returned search terms were across regime/therapy and procedures


# From `docs/psy_tx_anx_dep_notes.qmd`

# About this document

This document compiles the list of recommended psychological therapies for Depression and Anxiety in the UK General practice. It benefits from relevant guidance from NICE for management and treatment of depression and anxiety, including:

-   [Depression in adults: treatment and management](https://www.nice.org.uk/guidance/ng222/chapter/Recommendations)
-   [Generalised anxiety disorder and panic disorder in adults: management](https://www.nice.org.uk/guidance/cg113/chapter/Recommendations)

Further, it highlights how psychological therapies are coded in SNOMED-CT using [Opencodelist](https://www.opencodelists.org), a platform based on OpenSafely for sharing and creating codelists.

## Psychological therapies for Depression

The psychological therapies below are offered uniquely or in combinations for management of depression, and sometimes with anti-depressant based on severity, needs and patient's preference

-   **Guided self-help**: Printed or digital self-help materials on key psychological therapies including cognitive behavioural therapy

-   **Cognitive Behavioural Therapy (CBT)**: Focuses on how thoughts and beliefs could be modified to reshape behaviour. CBT is offered either individually or in group depending on patient's preference

-   **Behavioural Activation**: Recommended for recognising patterns in activities that affect mood and avoidance, and developing practical plans to reduce avoidance and improve mood. It can be provided individually or in group

-   **Group Exercise**: Focuses on group physical activity to benefit from peer support

-   **Group mindfulness and meditation**: Uses a programme such as mindfulness-based cognitive therapy. It is designed to increase awareness and recognition of thoughts and feelings

-   **Interpersonal psychotherapy**: Focuses on identifying how interpersonal relationships or circumstances are related to feelings of depression and modifying interpersonal responses

-   **Counselling**: Helps emotional processing, identification of solutions and coping mechanisms

-   **Short-term psychodynamic psychotherapy (STPP)**: Useful for recognising difficult feelings in significant relationships and and stressful situations

-   **Individual problem solving**: Targets identification of problems, generating and implementing alternative solutions

-   **Behavioural couples therapy**: Targets solving relationship challenges contributing to depression

-   **Electroconvulsive therapy**: It involves sending small electrical current through the brain to intentionally trigger a brief seizure

-   **Transcranial Magnetic Therapy**: Uses magnetic field to stimulate nerve cells in the brain, especially those involved in mood regulation

## Psychological therapies for Anxiety (Generalised Anxiety Disorder and Panic Disorder)

A step-care model is recommended by NICE for the management of anxiety. The model recommends range of low-intensity to high-intensity psychological therapies based on severity

Low-intensity therapies (first-line intervention following monitoring)

-   **Individual guided self-help**

-   **Individual non-facilitated self-help**

-   **Psycho-education**

High-intensity therapies

-   **Cognitive Behavioural Therapy**

-   **Applied Relaxation**: Involves learning muscle relaxation techniques during anxiousness or in situations that could trigger anxiousness

## Coding of psychological therapies within SNOMED-CT

This section highlights preliminary insights on how the psychological therapies are coded in SNOMED-CT

-   Returned search terms for therapies such as CBT, Behavioural Activation, Exercise therapy, Interpersonal psychotherapy and applied relaxation are not specific to anxiety or depression. This implies that pattern of coding for psychological therapies should be interpreted cautiously

-   Returned search terms were across regime/therapy and procedures
Footer



# Approach to categorise treatment codes

## Analytical approach

To analyise the code usage for psycholocal therapies, we are categorising the differnt codes into subcategories based on:

- signposting/referrals
- seen by psychologist
- psychological therapy started/ended
- everything else?
- low vs high intensity
- therapy indication (e.g., for depression, anxiety, or both)